# Generated by Django 2.2.13 on 2020-07-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('send_now', models.BooleanField()),
                ('send_datetime', models.DateTimeField()),
                ('send_to_all_participant', models.BooleanField()),
                ('send_to_newsletter_subscriber', models.BooleanField()),
                ('send_yn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
    ]
