# Generated by Django 2.2.13 on 2020-08-09 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='send_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 0, 0)),
        ),
    ]
