# Generated by Django 2.2.13 on 2020-07-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='sender_name',
            field=models.CharField(default='Pycon Korea', max_length=100),
        ),
    ]
