# Generated by Django 2.2.13 on 2020-08-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_auto_20200809_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email_address',
            field=models.EmailField(help_text='소식을 받을 이메일 주소', max_length=254),
        ),
    ]
