# Generated by Django 2.2.13 on 2020-07-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_auto_20200711_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
