# Generated by Django 2.2.13 on 2020-09-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_auto_20200830_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='agree_coc',
            field=models.BooleanField(default=False, help_text='참가자 슬랙 초대용 CoC 동의 여부'),
        ),
    ]
