# Generated by Django 2.2.10 on 2020-02-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='desc_en',
            field=models.TextField(blank=True, help_text='후원사 설명입니다. 이 설명은 홈페이지에 게시됩니다.', null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='desc_ko',
            field=models.TextField(blank=True, help_text='후원사 설명입니다. 이 설명은 홈페이지에 게시됩니다.', null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='name_en',
            field=models.CharField(blank=True, help_text='후원사 이름입니다. 서비스나 회사 이름이 될 수 있습니다.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='name_ko',
            field=models.CharField(blank=True, help_text='후원사 이름입니다. 서비스나 회사 이름이 될 수 있습니다.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sponsorlevel',
            name='desc_en',
            field=models.TextField(blank=True, help_text='후원 혜택을 입력하면 될 거 같아요 :) 후원사가 등급을 정할 때 볼 문구입니다.', null=True),
        ),
        migrations.AddField(
            model_name='sponsorlevel',
            name='desc_ko',
            field=models.TextField(blank=True, help_text='후원 혜택을 입력하면 될 거 같아요 :) 후원사가 등급을 정할 때 볼 문구입니다.', null=True),
        ),
        migrations.AddField(
            model_name='sponsorlevel',
            name='name_en',
            field=models.CharField(blank=True, default='', help_text='후원 등급명', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sponsorlevel',
            name='name_ko',
            field=models.CharField(blank=True, default='', help_text='후원 등급명', max_length=255, null=True),
        ),
    ]
