# Generated by Django 2.2.13 on 2020-07-09 09:54

from django.db import migrations, models
import sponsor.models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0002_auto_20200622_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='business_registration_file',
            field=models.FileField(blank=True, help_text='후원사 사업자 등록증 스캔본입니다. 세금 계산서 발급에 사용됩니다.', null=True, upload_to=sponsor.models.registration_file_upload_to),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='business_registration_number',
            field=models.CharField(blank=True, help_text='후원사 사업자 등록번호입니다. 세금 계산서 발급에 사용됩니다.', max_length=100, null=True),
        ),
    ]
