# Generated by Django 2.2.10 on 2020-03-08 07:31

from django.db import migrations, models
import django.db.models.deletion
import sponsor.models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0002_auto_20200228_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='comment',
            field=models.TextField(blank=True, help_text='파이콘 한국 준비위원회에게 행사나 후원 관련해 전달할 내용을 추가로 기입합니다. 이 내용은 홈페이지에 게시되지 않습니다.', null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='accepted',
            field=models.BooleanField(default=False, help_text='후원사로 확정되었을 경우 True로 설정됩니다.'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='business_registration_file',
            field=models.FileField(help_text='후원사 사업자 등록증 스캔본입니다. 세금 계산서 발급에 사용됩니다.', upload_to=sponsor.models.registration_file_upload_to),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='business_registration_number',
            field=models.CharField(help_text='후원사 사업자 등록번호입니다. 세금 계산서 발급에 사용됩니다.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='level',
            field=models.ForeignKey(blank=True, help_text='후원을 원하시는 등급입니다. 모두 판매된 등급은 선택할 수 없습니다.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsor.SponsorLevel'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='manager_email',
            field=models.CharField(help_text='후원 담당자의 이메일 주소를 입력해주십시오.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='manager_name',
            field=models.CharField(help_text='준비위원회와 후원과 관련된 논의를 진행할 담당자의 이름을 입력해주십시오.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(blank=True, help_text='후원사의 이름입니다. 서비스나 회사 이름이 될 수 있습니다.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name_en',
            field=models.CharField(blank=True, help_text='후원사의 이름입니다. 서비스나 회사 이름이 될 수 있습니다.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name_ko',
            field=models.CharField(blank=True, help_text='후원사의 이름입니다. 서비스나 회사 이름이 될 수 있습니다.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='submitted',
            field=models.BooleanField(default=False, help_text='사용자가 제출했는지 여부를 저장합니다. 요청이 제출되면 준비위원회에서 검토하고 받아들일지를 결정합니다'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='url',
            field=models.CharField(blank=True, help_text='파이콘 홈페이지에 공개되는 후원사 홈페이지 주소입니다.', max_length=255, null=True),
        ),
    ]
