# Generated by Django 2.2.10 on 2020-03-17 08:19

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import sponsor.models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0003_auto_20200308_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='level',
            field=models.ForeignKey(blank=True, help_text='후원을 원하시는 등급을 선택해주십시오. 모두 판매된 등급은 선택할 수 없습니다.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsor.SponsorLevel'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='홈페이지에 공개되는 후원사 로고 이미지입니다.', null=True, upload_to=sponsor.models.logo_image_upload_to),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='manager_email',
            field=models.CharField(help_text='입력하신 메일로 후원과 관련된 안내 메일이나 문의를 보낼 예정입니다. 후원 담당자의 이메일 주소를 입력해주십시오.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(default='', help_text='후원사의 이름입니다. 서비스나 회사 이름이 될 수 있습니다.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name_en',
            field=models.CharField(help_text='후원사의 이름입니다. 서비스나 회사 이름이 될 수 있습니다.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name_ko',
            field=models.CharField(help_text='후원사의 이름입니다. 서비스나 회사 이름이 될 수 있습니다.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='slug',
            field=models.SlugField(blank=True, help_text='후원사 상세 페이지의 path로 사용됩니다', max_length=100, null=True),
        ),
    ]
