# Generated by Django 2.2.10 on 2020-06-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0004_auto_20200317_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='comment',
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='slug',
            field=models.SlugField(blank=True, help_text='후원사 상세 페이지의 path로 사용됩니다.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='submitted',
            field=models.BooleanField(default=False, help_text='사용자가 제출했는지 여부를 저장합니다. 요청이 제출되면 준비위원회에서 검토하고 받아들일지를 결정합니다.'),
        ),
    ]
