# Generated by Django 2.2.10 on 2020-06-20 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0006_sponsor_virtual_hall_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='virtual_hall_content',
            new_name='virtual_booth_content',
        ),
    ]
