# Generated by Django 2.2.10 on 2020-06-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0007_auto_20200620_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='accepted',
            field=models.BooleanField(default=False, help_text='후원사 신청이 접수되었고, 입금 대기 상태인 경우 True로 설정됩니다.'),
        ),
    ]
