# Generated by Django 2.2.10 on 2020-05-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_announcement_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='announce_after',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='created',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='desc_en',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='desc_ko',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='modified',
        ),
        migrations.AddField(
            model_name='announcement',
            name='active',
            field=models.BooleanField(default=True, help_text='True면 공지사항이 노출됩니다.'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='url',
            field=models.URLField(help_text='공지 내용을 볼 수 있는 링크입니다. 주로 페이스북 공지 링크가 들어가게 됩니다.', max_length=500),
        ),
    ]
