# Generated by Django 2.2.10 on 2020-06-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='language',
            field=models.CharField(choices=[('', '---------'), ('K', 'Korean'), ('E', 'English')], default='', max_length=1),
        ),
    ]
