# Generated by Django 2.2.10 on 2020-06-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='category',
            field=models.CharField(choices=[('', '---------'), ('PL', 'Python Library'), ('DM', 'Development Method with Python'), ('DA', 'Data Analytics'), ('LS', 'Life / Social'), ('CV', 'Computer Vision'), ('RE', 'Robotics / Embedded System'), ('DG', 'Data Gathering'), ('BC', 'Blockchain'), ('PC', 'Python Community'), ('WS', 'Web Service'), ('DL', 'Deep Learning & AI'), ('PF', 'Python Core & Fundamental'), ('DS', 'Data Science'), ('etc', 'etc')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='language',
            field=models.CharField(choices=[('', '---------'), ('K', 'Korean'), ('E', 'English')], default='', max_length=1),
        ),
    ]
