# Generated by Django 2.2.13 on 2020-07-14 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_openreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='openreview',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.ProgramCategory'),
        ),
        migrations.AddField(
            model_name='openreview',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
