# Generated by Django 2.2.13 on 2020-07-11 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_openreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='openreview',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.ProgramCategory'),
        ),
        migrations.AddField(
            model_name='openreview',
            name='language',
            field=models.CharField(choices=[('', '---------'), ('K', 'Korean'), ('E', 'English')], default='', max_length=1),
        ),
    ]
