# Generated by Django 2.2.10 on 2020-06-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_auto_20200607_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.CharField(choices=[('S', '25min'), ('L', '40min')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='category',
            field=models.CharField(blank=True, choices=[('', '---------'), ('PL', 'Python Library'), ('DM', 'Development Method with Python'), ('DA', 'Data Analytics'), ('LS', 'Life / Social'), ('CV', 'Computer Vision'), ('RE', 'Robotics / Embedded System'), ('DG', 'Data Gathering'), ('BC', 'Blockchain'), ('PC', 'Python Community'), ('WS', 'Web Service'), ('DL', 'Deep Learning & AI'), ('PF', 'Python Core & Fundamental'), ('DS', 'Data Science'), ('etc', 'etc')], default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='duration',
            field=models.CharField(choices=[('S', '25min'), ('L', '40min')], max_length=1),
        ),
    ]
