# Generated by Django 2.2.10 on 2020-06-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20200613_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='category',
            field=models.CharField(blank=True, choices=[('PL', 'Python Library'), ('DM', 'Development Method with Python'), ('DA', 'Data Analytics'), ('LS', 'Life / Social'), ('CV', 'Computer Vision'), ('RE', 'Robotics / Embedded System'), ('DG', 'Data Gathering'), ('BC', 'Blockchain'), ('PC', 'Python Community'), ('WS', 'Web Service'), ('DL', 'Deep Learning & AI'), ('PF', 'Python Core & Fundamental'), ('DS', 'Data Science'), ('etc', 'etc')], default='', max_length=25, null=True),
        ),
    ]
