# Generated by Django 2.2.13 on 2020-07-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20200711_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openreview',
            name='language',
        ),
    ]
