# Generated by Django 2.2.10 on 2020-06-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20200613_2001'),
        ('program', '0004_auto_20200613_2012'),
    ]

    operations = [
    ]
