# Generated by Django 2.2.13 on 2020-08-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_auto_20200714_1757'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sprintcheckin',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sprintcheckin',
            name='sprint',
        ),
        migrations.RemoveField(
            model_name='sprintcheckin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sprintproposal',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='tutorialcheckin',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tutorialcheckin',
            name='tutorial',
        ),
        migrations.RemoveField(
            model_name='tutorialcheckin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tutorialproposal',
            name='option',
        ),
        migrations.RemoveField(
            model_name='tutorialproposal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='program',
            name='rooms',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='SprintCheckin',
        ),
        migrations.DeleteModel(
            name='SprintProposal',
        ),
        migrations.DeleteModel(
            name='TutorialCheckin',
        ),
        migrations.DeleteModel(
            name='TutorialProposal',
        ),
    ]
