# Generated by Django 2.2.13 on 2020-08-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_auto_20200819_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
