# Generated by Django 2.2.13 on 2020-08-22 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_proposal_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='category',
        ),
        migrations.RemoveField(
            model_name='program',
            name='date',
        ),
        migrations.RemoveField(
            model_name='program',
            name='speakers',
        ),
        migrations.RemoveField(
            model_name='program',
            name='times',
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
    ]
