# Generated by Django 2.2.13 on 2020-08-22 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_auto_20200822_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programtime',
            name='day',
        ),
        migrations.DeleteModel(
            name='ProgramDate',
        ),
        migrations.DeleteModel(
            name='ProgramTime',
        ),
    ]
