# Generated by Django 2.2.10 on 2020-06-13 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_auto_20200613_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='category',
        ),
    ]
