# Generated by Django 2.2.10 on 2020-06-15 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_remove_proposal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='category',
            field=models.ForeignKey(blank=True, default=14, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='program.ProgramCategory'),
        ),
    ]
