# Generated by Django 2.2.13 on 2020-08-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_auto_20200822_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='introduction',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
