# Generated by Django 2.2.10 on 2020-06-15 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_auto_20200615_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='category',
            field=models.ForeignKey(blank=True, default=14, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='program.ProgramCategory', to_field='slug'),
        ),
    ]
