# Generated by Django 2.2.13 on 2020-08-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_auto_20200822_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='video_open_at',
            field=models.DateTimeField(blank=True, help_text='파이콘 한국 유튜브에 공개되는 시간', null=True),
        ),
    ]
