# Generated by Django 2.2.10 on 2020-06-20 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0010_auto_20200615_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=2000)),
                ('category', models.ForeignKey(default=14, on_delete=django.db.models.deletion.SET_DEFAULT, to='program.ProgramCategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
