# Generated by Django 2.2.13 on 2020-08-25 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0011_auto_20200822_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='스프린트 제목', max_length=255)),
                ('desc', models.TextField(blank=True, help_text='스프린트 설명', max_length=4000, null=True)),
                ('url', models.CharField(blank=True, help_text='홈페이지에 공개되는 스프린트 관련 주소입니다.', max_length=255, null=True)),
                ('creator', models.ForeignKey(help_text='스프린트를 등록한 유저', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
