# Generated by Django 2.2.13 on 2020-08-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0013_sprint_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='language',
            field=models.CharField(blank=True, help_text='스프린트를 진행할 프로그래밍 언어', max_length=255, null=True),
        ),
    ]
