# Generated by Django 2.2.13 on 2020-08-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0014_sprint_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='brief',
            field=models.CharField(blank=True, help_text='스프린트에 대한 짧은 설명', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='desc',
            field=models.TextField(blank=True, help_text='스프린트에 대한 자세한 설명', max_length=4000, null=True),
        ),
    ]
