# Generated by Django 2.2.13 on 2020-09-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0016_remove_sprint_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='track_num',
            field=models.IntegerField(blank=True, help_text='트랙 번호', null=True),
        ),
    ]
