# Generated by Django 2.2.13 on 2020-09-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0017_proposal_track_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightningtalk',
            name='video_url',
            field=models.CharField(default='', max_length=511),
        ),
        migrations.AlterField(
            model_name='lightningtalk',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lightningtalk',
            name='slide_url',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='lightningtalk',
            name='title',
            field=models.CharField(help_text='라이트닝 토크 제목', max_length=255),
        ),
    ]
