# Generated by Django 2.2.13 on 2020-09-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0020_auto_20200903_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightningtalk',
            name='brief',
            field=models.TextField(blank=True, help_text='라이트닝 토크 소개 문구', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='lightningtalk',
            name='comment',
            field=models.TextField(blank=True, help_text='준비위원회에게 남기고 싶은 말', null=True),
        ),
    ]
