# Generated by Django 2.2.13 on 2020-09-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0021_auto_20200906_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='introduction',
            field=models.TextField(blank=True, help_text='발표 소개 페이지에 들어가는 내용입니다. 변경 사항은 최대 60분 이내에 적용됩니다.', max_length=1000, null=True),
        ),
    ]
