# Generated by Django 2.2.10 on 2020-02-24 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('conference', '컨퍼런스'), ('tutorial', '튜토리얼'), ('youngcoder', '영코더'), ('babycare', '아이돌봄')], default='conference', max_length=15)),
                ('conference_type', models.CharField(blank=True, choices=[('earlybird', '얼리버드'), ('regular', '일반'), ('company', '법인'), ('patron', '개인후원')], max_length=15, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField()),
                ('has_additional_price', models.BooleanField(default=False)),
                ('total', models.IntegerField(default=500)),
                ('is_cancelable', models.BooleanField(default=False)),
                ('cancelable_date', models.DateTimeField(null=True)),
                ('begin_at', models.DateTimeField(null=True)),
                ('closed_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_uid', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('top_size', models.CharField(blank=True, choices=[('small', 'S(85)'), ('medium', 'M(90)'), ('large', 'L(95)'), ('xlarge', 'XL(100)'), ('2xlarge', '2XL(105)'), ('3xlarge', '3XL(110)'), ('4xlarge', '4XL(115)')], default=None, max_length=20, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('transaction_code', models.CharField(blank=True, max_length=36)),
                ('additional_price', models.PositiveIntegerField(default=0)),
                ('payment_method', models.CharField(choices=[('card-korean', 'Credit Card only for Korean'), ('card-foreign', 'Credit Card for Foreign')], default='card-korean', max_length=20)),
                ('payment_status', models.CharField(choices=[('ready', 'Ready'), ('paid', 'Paid'), ('deleted', 'Deleted'), ('cancelled', 'Cancelled')], default='ready', max_length=10)),
                ('payment_message', models.CharField(blank=True, max_length=255, null=True)),
                ('vbank_num', models.CharField(blank=True, max_length=255, null=True)),
                ('vbank_name', models.CharField(blank=True, max_length=20, null=True)),
                ('vbank_date', models.CharField(blank=True, max_length=50, null=True)),
                ('vbank_holder', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('confirmed', models.DateTimeField(blank=True, null=True)),
                ('canceled', models.DateTimeField(blank=True, null=True)),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Option')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManualPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('merchant_uid', models.CharField(blank=True, db_index=True, max_length=32)),
                ('imp_uid', models.CharField(blank=True, max_length=32, null=True)),
                ('transaction_code', models.CharField(blank=True, max_length=36)),
                ('payment_method', models.CharField(choices=[('card', 'Credit Card')], default='card', max_length=20)),
                ('payment_status', models.CharField(choices=[('ready', 'Ready'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='ready', max_length=10)),
                ('payment_message', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('confirmed', models.DateTimeField(blank=True, null=True)),
                ('canceled', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssueTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('issuer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Registration')),
            ],
        ),
    ]
