# Generated by Django 2.2.13 on 2020-08-19 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_purchase_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 17, 27, 30, 678144)),
        ),
    ]
