# Generated by Django 2.2.13 on 2020-08-24 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200822_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualpayment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='option',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
        migrations.DeleteModel(
            name='IssueTicket',
        ),
        migrations.DeleteModel(
            name='ManualPayment',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
