# Generated by Django 2.2.13 on 2020-08-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20200825_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='agree_coc',
            field=models.BooleanField(default=False),
        ),
    ]
