# Generated by Django 2.2.13 on 2020-09-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_ticket_agree_coc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
