# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-15 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0028_merge_20180723_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='event_type',
            field=models.CharField(choices=[('conference', '컨퍼런스'), ('tutorial', '튜토리얼'), ('youngcoder', '영코더'), ('babycare', '아이돌봄')], default='conference', max_length=15),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(choices=[('card-korean', 'Credit Card only for Korean'), ('card-foreign', 'Credit Card for Foreign')], default='card-korean', max_length=20),
        ),
    ]
