# Generated by Django 2.2.10 on 2020-02-28 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyconkr', '0002_profile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
