# Generated by Django 2.2.10 on 2020-02-28 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyconkr', '0004_auto_20200228_1559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
