# Generated by Django 2.2.10 on 2020-02-15 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyconkr', '0022_auto_20200215_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pyconkr.Program'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pyconkr.ProgramCategory'),
        ),
        migrations.AlterField(
            model_name='program',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pyconkr.ProgramDate'),
        ),
        migrations.AlterField(
            model_name='programtime',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pyconkr.ProgramDate'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pyconkr.SponsorLevel'),
        ),
        migrations.AlterField(
            model_name='sprintcheckin',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pyconkr.SprintProposal'),
        ),
        migrations.AlterField(
            model_name='sprintcheckin',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorialcheckin',
            name='tutorial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pyconkr.TutorialProposal'),
        ),
        migrations.AlterField(
            model_name='tutorialcheckin',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='option',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Option', verbose_name='구매 티켓 종류'),
        ),
    ]
