# Generated by Django 2.2.13 on 2020-07-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agreement_receive_advertising_info',
            field=models.BooleanField(default=False),
        ),
    ]
