# Generated by Django 2.2.13 on 2020-08-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_agreement_receive_advertising_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
