# Generated by Django 2.2.13 on 2020-09-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profile_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='이 내용이 개인 후원자 목록에 노출됩니다. 변경 사항은 최대 60분 이내에 적용됩니다.', max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio_en',
            field=models.TextField(blank=True, help_text='이 내용이 개인 후원자 목록에 노출됩니다. 변경 사항은 최대 60분 이내에 적용됩니다.', max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio_ko',
            field=models.TextField(blank=True, help_text='이 내용이 개인 후원자 목록에 노출됩니다. 변경 사항은 최대 60분 이내에 적용됩니다.', max_length=4000, null=True),
        ),
    ]
