# Generated by Django 2.2.13 on 2020-09-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phrase',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
