# Generated by Django 2.2.13 on 2020-09-24 00:49

from django.db import migrations
import sorl.thumbnail.fields
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200918_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='image_ori',
        ),
        migrations.AddField(
            model_name='profile',
            name='image_small',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=user.models.profile_image),
        ),
    ]
